name: phanpy
description: A minimalistic opinionated Mastodon mobile client

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.2.2
  photo_manager: ^2.6.0
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#B7CDF9"
  image: "assets/logo.png"
